[package]
name = "schwab_api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.7", features = ["chrono_0_4"] }
governor = "0.6"
chrono = { version = "0.4", features = ["serde", "clock"] }
oauth2 = "4.4"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
dirs = "5.0"
url = "2.5"
axum = { version = "0.7", features = ["macros"] }
axum-server = { version = "0.6", features = ["tls-rustls"] }
thiserror = "1.0"
open = "5"
async-channel = "2.2"

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
serde_test = "1.0"
mockito = "1.4"
pretty_assertions = "1.4"